/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TransitionHistoryListResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TransitionHistoryListResponseFromJSON,
    TransitionHistoryListResponseToJSON,
} from '../models/index';

export interface GetJourneyInstanceHistoryRequest {
    instanceId: string;
    from?: Date;
    to?: Date;
    eventType?: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class JourneyInstanceHistoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for getJourneyInstanceHistory without sending the request
     */
    async getJourneyInstanceHistoryRequestOpts(requestParameters: GetJourneyInstanceHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instanceId'] == null) {
            throw new runtime.RequiredError(
                'instanceId',
                'Required parameter "instanceId" was null or undefined when calling getJourneyInstanceHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['eventType'] = requestParameters['eventType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/journey-instances/{instanceId}/history`;
        urlPath = urlPath.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters['instanceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the complete transition history for a specific journey instance in chronological order
     * Get transition history for a journey instance
     */
    async getJourneyInstanceHistoryRaw(requestParameters: GetJourneyInstanceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransitionHistoryListResponse>> {
        const requestOptions = await this.getJourneyInstanceHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransitionHistoryListResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the complete transition history for a specific journey instance in chronological order
     * Get transition history for a journey instance
     */
    async getJourneyInstanceHistory(requestParameters: GetJourneyInstanceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransitionHistoryListResponse> {
        const response = await this.getJourneyInstanceHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
