/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { TransitionHistoryListResponse } from '../models';
/**
 * JourneyInstanceHistoryApi - axios parameter creator
 */
export const JourneyInstanceHistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstanceHistory: async (instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('getJourneyInstanceHistory', 'instanceId', instanceId)
            const localVarPath = `/journey-instances/{instanceId}/history`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (eventType !== undefined) {
                localVarQueryParameter['eventType'] = eventType;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyInstanceHistoryApi - functional programming interface
 */
export const JourneyInstanceHistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyInstanceHistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransitionHistoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstanceHistoryApi.getJourneyInstanceHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyInstanceHistoryApi - factory interface
 */
export const JourneyInstanceHistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyInstanceHistoryApiFp(configuration)
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<TransitionHistoryListResponse> {
            return localVarFp.getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyInstanceHistoryApi - object-oriented interface
 */
export class JourneyInstanceHistoryApi extends BaseAPI {
    /**
     * Retrieves the complete transition history for a specific journey instance in chronological order
     * @summary Get transition history for a journey instance
     * @param {string} instanceId ID of the journey instance
     * @param {string} [from] Filter history from this timestamp (ISO 8601)
     * @param {string} [to] Filter history to this timestamp (ISO 8601)
     * @param {string} [eventType] Filter by specific event type
     * @param {number} [limit] Maximum number of events to return
     * @param {number} [offset] Number of events to skip (for pagination)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return JourneyInstanceHistoryApiFp(this.configuration).getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }
}

