/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateJourneyDefinitionRequest } from '../models';
// @ts-ignore
import type { JourneyDefinitionResponse } from '../models';
/**
 * JourneyDefinitionsApi - axios parameter creator
 */
export const JourneyDefinitionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyDefinition: async (createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createJourneyDefinitionRequest' is not null or undefined
            assertParamExists('createJourneyDefinition', 'createJourneyDefinitionRequest', createJourneyDefinitionRequest)
            const localVarPath = `/journeys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createJourneyDefinitionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a journey definition
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyDefinition: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteJourneyDefinition', 'id', id)
            const localVarPath = `/journeys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyDefinitionsByCode: async (journeyCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyCode' is not null or undefined
            assertParamExists('getJourneyDefinitionsByCode', 'journeyCode', journeyCode)
            const localVarPath = `/journeys/{journeyCode}`
                .replace(`{${"journeyCode"}}`, encodeURIComponent(String(journeyCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJourneyDefinitions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/journeys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a journey definition
         * @param {string} id 
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateJourneyDefinition: async (id: string, createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateJourneyDefinition', 'id', id)
            // verify required parameter 'createJourneyDefinitionRequest' is not null or undefined
            assertParamExists('updateJourneyDefinition', 'createJourneyDefinitionRequest', createJourneyDefinitionRequest)
            const localVarPath = `/journeys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createJourneyDefinitionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyDefinitionsApi - functional programming interface
 */
export const JourneyDefinitionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyDefinitionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyDefinitionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJourneyDefinition(createJourneyDefinitionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.createJourneyDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a journey definition
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteJourneyDefinition(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.deleteJourneyDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<JourneyDefinitionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyDefinitionsByCode(journeyCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.getJourneyDefinitionsByCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJourneyDefinitions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<JourneyDefinitionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJourneyDefinitions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.listJourneyDefinitions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a journey definition
         * @param {string} id 
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateJourneyDefinition(id: string, createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyDefinitionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateJourneyDefinition(id, createJourneyDefinitionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.updateJourneyDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyDefinitionsApi - factory interface
 */
export const JourneyDefinitionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyDefinitionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyDefinitionResponse> {
            return localVarFp.createJourneyDefinition(createJourneyDefinitionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a journey definition
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteJourneyDefinition(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<JourneyDefinitionResponse>> {
            return localVarFp.getJourneyDefinitionsByCode(journeyCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJourneyDefinitions(options?: RawAxiosRequestConfig): AxiosPromise<Array<JourneyDefinitionResponse>> {
            return localVarFp.listJourneyDefinitions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a journey definition
         * @param {string} id 
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateJourneyDefinition(id: string, createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyDefinitionResponse> {
            return localVarFp.updateJourneyDefinition(id, createJourneyDefinitionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyDefinitionsApi - object-oriented interface
 */
export class JourneyDefinitionsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new journey definition
     * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).createJourneyDefinition(createJourneyDefinitionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a journey definition
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).deleteJourneyDefinition(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all versions of a journey definition
     * @param {string} journeyCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).getJourneyDefinitionsByCode(journeyCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all journey definitions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listJourneyDefinitions(options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).listJourneyDefinitions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a journey definition
     * @param {string} id 
     * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateJourneyDefinition(id: string, createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).updateJourneyDefinition(id, createJourneyDefinitionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

