/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateJourneyInstanceRequest,
  EventRequest,
  JourneyInstanceResponse,
} from '../models/index';
import {
    CreateJourneyInstanceRequestFromJSON,
    CreateJourneyInstanceRequestToJSON,
    EventRequestFromJSON,
    EventRequestToJSON,
    JourneyInstanceResponseFromJSON,
    JourneyInstanceResponseToJSON,
} from '../models/index';

export interface CreateJourneyInstanceOperationRequest {
    createJourneyInstanceRequest: CreateJourneyInstanceRequest;
}

export interface GetJourneyInstanceRequest {
    instanceId: string;
}

export interface SendEventRequest {
    instanceId: string;
    eventRequest: EventRequest;
}

/**
 * 
 */
export class JourneyInstancesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createJourneyInstance without sending the request
     */
    async createJourneyInstanceRequestOpts(requestParameters: CreateJourneyInstanceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createJourneyInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'createJourneyInstanceRequest',
                'Required parameter "createJourneyInstanceRequest" was null or undefined when calling createJourneyInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/journey-instances`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJourneyInstanceRequestToJSON(requestParameters['createJourneyInstanceRequest']),
        };
    }

    /**
     * Start a new journey instance
     */
    async createJourneyInstanceRaw(requestParameters: CreateJourneyInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JourneyInstanceResponse>> {
        const requestOptions = await this.createJourneyInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JourneyInstanceResponseFromJSON(jsonValue));
    }

    /**
     * Start a new journey instance
     */
    async createJourneyInstance(requestParameters: CreateJourneyInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JourneyInstanceResponse> {
        const response = await this.createJourneyInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJourneyInstance without sending the request
     */
    async getJourneyInstanceRequestOpts(requestParameters: GetJourneyInstanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instanceId'] == null) {
            throw new runtime.RequiredError(
                'instanceId',
                'Required parameter "instanceId" was null or undefined when calling getJourneyInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/journey-instances/{instanceId}`;
        urlPath = urlPath.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters['instanceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get journey instance by id
     */
    async getJourneyInstanceRaw(requestParameters: GetJourneyInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JourneyInstanceResponse>> {
        const requestOptions = await this.getJourneyInstanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JourneyInstanceResponseFromJSON(jsonValue));
    }

    /**
     * Get journey instance by id
     */
    async getJourneyInstance(requestParameters: GetJourneyInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JourneyInstanceResponse> {
        const response = await this.getJourneyInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEvent without sending the request
     */
    async sendEventRequestOpts(requestParameters: SendEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instanceId'] == null) {
            throw new runtime.RequiredError(
                'instanceId',
                'Required parameter "instanceId" was null or undefined when calling sendEvent().'
            );
        }

        if (requestParameters['eventRequest'] == null) {
            throw new runtime.RequiredError(
                'eventRequest',
                'Required parameter "eventRequest" was null or undefined when calling sendEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/journey-instances/{instanceId}/events`;
        urlPath = urlPath.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters['instanceId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventRequestToJSON(requestParameters['eventRequest']),
        };
    }

    /**
     * Send event to a journey instance
     */
    async sendEventRaw(requestParameters: SendEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JourneyInstanceResponse>> {
        const requestOptions = await this.sendEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JourneyInstanceResponseFromJSON(jsonValue));
    }

    /**
     * Send event to a journey instance
     */
    async sendEvent(requestParameters: SendEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JourneyInstanceResponse> {
        const response = await this.sendEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
