/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateJourneyInstanceRequest } from '../models';
// @ts-ignore
import type { EventRequest } from '../models';
// @ts-ignore
import type { JourneyInstanceResponse } from '../models';
/**
 * JourneyInstancesApi - axios parameter creator
 */
export const JourneyInstancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyInstance: async (createJourneyInstanceRequest: CreateJourneyInstanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createJourneyInstanceRequest' is not null or undefined
            assertParamExists('createJourneyInstance', 'createJourneyInstanceRequest', createJourneyInstanceRequest)
            const localVarPath = `/journey-instances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createJourneyInstanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstance: async (instanceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('getJourneyInstance', 'instanceId', instanceId)
            const localVarPath = `/journey-instances/{instanceId}`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEvent: async (instanceId: string, eventRequest: EventRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('sendEvent', 'instanceId', instanceId)
            // verify required parameter 'eventRequest' is not null or undefined
            assertParamExists('sendEvent', 'eventRequest', eventRequest)
            const localVarPath = `/journey-instances/{instanceId}/events`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eventRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyInstancesApi - functional programming interface
 */
export const JourneyInstancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyInstancesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJourneyInstance(createJourneyInstanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.createJourneyInstance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyInstance(instanceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.getJourneyInstance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEvent(instanceId, eventRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.sendEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyInstancesApi - factory interface
 */
export const JourneyInstancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyInstancesApiFp(configuration)
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.createJourneyInstance(createJourneyInstanceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.getJourneyInstance(instanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.sendEvent(instanceId, eventRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyInstancesApi - object-oriented interface
 */
export class JourneyInstancesApi extends BaseAPI {
    /**
     * 
     * @summary Start a new journey instance
     * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).createJourneyInstance(createJourneyInstanceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get journey instance by id
     * @param {string} instanceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).getJourneyInstance(instanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Send event to a journey instance
     * @param {string} instanceId 
     * @param {EventRequest} eventRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).sendEvent(instanceId, eventRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

