/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateJourneyDefinitionRequest,
  JourneyDefinitionResponse,
} from '../models/index';
import {
    CreateJourneyDefinitionRequestFromJSON,
    CreateJourneyDefinitionRequestToJSON,
    JourneyDefinitionResponseFromJSON,
    JourneyDefinitionResponseToJSON,
} from '../models/index';

export interface CreateJourneyDefinitionOperationRequest {
    createJourneyDefinitionRequest: CreateJourneyDefinitionRequest;
}

export interface GetJourneyDefinitionsByCodeRequest {
    journeyCode: string;
}

/**
 * 
 */
export class JourneyDefinitionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createJourneyDefinition without sending the request
     */
    async createJourneyDefinitionRequestOpts(requestParameters: CreateJourneyDefinitionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createJourneyDefinitionRequest'] == null) {
            throw new runtime.RequiredError(
                'createJourneyDefinitionRequest',
                'Required parameter "createJourneyDefinitionRequest" was null or undefined when calling createJourneyDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/journeys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJourneyDefinitionRequestToJSON(requestParameters['createJourneyDefinitionRequest']),
        };
    }

    /**
     * Create a new journey definition
     */
    async createJourneyDefinitionRaw(requestParameters: CreateJourneyDefinitionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JourneyDefinitionResponse>> {
        const requestOptions = await this.createJourneyDefinitionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JourneyDefinitionResponseFromJSON(jsonValue));
    }

    /**
     * Create a new journey definition
     */
    async createJourneyDefinition(requestParameters: CreateJourneyDefinitionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JourneyDefinitionResponse> {
        const response = await this.createJourneyDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJourneyDefinitionsByCode without sending the request
     */
    async getJourneyDefinitionsByCodeRequestOpts(requestParameters: GetJourneyDefinitionsByCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['journeyCode'] == null) {
            throw new runtime.RequiredError(
                'journeyCode',
                'Required parameter "journeyCode" was null or undefined when calling getJourneyDefinitionsByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/journeys/{journeyCode}`;
        urlPath = urlPath.replace(`{${"journeyCode"}}`, encodeURIComponent(String(requestParameters['journeyCode'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all versions of a journey definition
     */
    async getJourneyDefinitionsByCodeRaw(requestParameters: GetJourneyDefinitionsByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<JourneyDefinitionResponse>>> {
        const requestOptions = await this.getJourneyDefinitionsByCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JourneyDefinitionResponseFromJSON));
    }

    /**
     * Get all versions of a journey definition
     */
    async getJourneyDefinitionsByCode(requestParameters: GetJourneyDefinitionsByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<JourneyDefinitionResponse>> {
        const response = await this.getJourneyDefinitionsByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listJourneyDefinitions without sending the request
     */
    async listJourneyDefinitionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/journeys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all journey definitions
     */
    async listJourneyDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<JourneyDefinitionResponse>>> {
        const requestOptions = await this.listJourneyDefinitionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JourneyDefinitionResponseFromJSON));
    }

    /**
     * List all journey definitions
     */
    async listJourneyDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<JourneyDefinitionResponse>> {
        const response = await this.listJourneyDefinitionsRaw(initOverrides);
        return await response.value();
    }

}
