/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateJourneyDefinitionRequest {
    'journeyCode': string;
    'name': string;
    'version': number;
    'states': Array<State>;
    'transitions': Array<TransitionRequest>;
}
export interface CreateJourneyInstanceRequest {
    'journeyCode': string;
    'version': number;
    'context'?: { [key: string]: any; };
}
export interface ErrorResponse {
    'error': ErrorResponseError;
}
export interface ErrorResponseError {
    /**
     * Error code
     */
    'code': string;
    /**
     * Human-readable error message
     */
    'message': string;
    /**
     * Additional error details
     */
    'details'?: { [key: string]: any; };
}
export interface EventInfo {
    /**
     * Type of the event that triggered the transition
     */
    'type': string;
    /**
     * Event-specific data
     */
    'data'?: { [key: string]: any; };
}
export interface EventRequest {
    'event': string;
    'payload'?: { [key: string]: any; };
}
export interface JourneyDefinitionResponse {
    'id'?: string;
    'journeyCode'?: string;
    'name'?: string;
    'version'?: number;
    'states'?: Array<State>;
    'transitions'?: Array<TransitionResponse>;
    'active'?: boolean;
    'createdAt'?: string;
}
export interface JourneyInstanceResponse {
    'instanceId'?: string;
    'journeyCode'?: string;
    'version'?: number;
    'currentState'?: string;
    'status'?: JourneyStatus;
    'createdAt'?: string;
    'updatedAt'?: string;
}



export const JourneyStatus = {
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED',
} as const;

export type JourneyStatus = typeof JourneyStatus[keyof typeof JourneyStatus];


export interface PaginationInfo {
    /**
     * Number of events returned in this page
     */
    'limit'?: number;
    /**
     * Number of events skipped
     */
    'offset'?: number;
    /**
     * Whether there are more events available
     */
    'hasNext'?: boolean;
    /**
     * Whether there are previous events available
     */
    'hasPrevious'?: boolean;
}
export interface State {
    /**
     * Unique identifier for the state (UUID v4). Auto-generated if not provided.
     */
    'id'?: string;
    'name': string;
    'type': StateType;
    'position'?: StatePosition;
}


/**
 * Visual editor position data (optional, for React Flow integration)
 */
export interface StatePosition {
    /**
     * X coordinate
     */
    'x': number;
    /**
     * Y coordinate
     */
    'y': number;
}

export const StateType = {
    Initial: 'INITIAL',
    Intermediate: 'INTERMEDIATE',
    Final: 'FINAL',
} as const;

export type StateType = typeof StateType[keyof typeof StateType];


export interface TransitionHistoryEventResponse {
    /**
     * Unique identifier for the history event
     */
    'id': string;
    /**
     * ID of the journey instance
     */
    'instanceId': string;
    /**
     * Previous state before transition
     */
    'fromState': string;
    /**
     * New state after transition
     */
    'toState': string;
    'event': EventInfo;
    /**
     * When the transition occurred (ISO 8601)
     */
    'timestamp': string;
    /**
     * Additional context information
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Sequence number for ordering same-millisecond events
     */
    'sequenceNumber'?: number;
}
export interface TransitionHistoryListResponse {
    /**
     * ID of the journey instance
     */
    'instanceId'?: string;
    'events'?: Array<TransitionHistoryEventResponse>;
    'pagination'?: PaginationInfo;
    /**
     * Total number of events in history
     */
    'totalCount'?: number;
}
export interface TransitionRequest {
    /**
     * Source state reference by name (legacy)
     */
    'source': string;
    /**
     * Target state reference by name (legacy)
     */
    'target': string;
    /**
     * Source state reference by ID (new, preferred). Takes precedence if both source and sourceStateId are provided.
     */
    'sourceStateId'?: string;
    /**
     * Target state reference by ID (new, preferred). Takes precedence if both target and targetStateId are provided.
     */
    'targetStateId'?: string;
    'event': string;
    /**
     * Optional SpEL expression for conditional transitions
     */
    'condition'?: string;
}
export interface TransitionResponse {
    /**
     * Source state reference by name (legacy)
     */
    'source'?: string;
    /**
     * Target state reference by name (legacy)
     */
    'target'?: string;
    /**
     * Source state reference by ID (new). Populated when available.
     */
    'sourceStateId'?: string;
    /**
     * Target state reference by ID (new). Populated when available.
     */
    'targetStateId'?: string;
    'event'?: string;
    /**
     * Optional SpEL expression for conditional transitions
     */
    'condition'?: string;
}

/**
 * JourneyDefinitionsApi - axios parameter creator
 */
export const JourneyDefinitionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyDefinition: async (createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createJourneyDefinitionRequest' is not null or undefined
            assertParamExists('createJourneyDefinition', 'createJourneyDefinitionRequest', createJourneyDefinitionRequest)
            const localVarPath = `/journeys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createJourneyDefinitionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a journey definition by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyDefinition: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteJourneyDefinition', 'id', id)
            const localVarPath = `/journeys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyDefinitionsByCode: async (journeyCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyCode' is not null or undefined
            assertParamExists('getJourneyDefinitionsByCode', 'journeyCode', journeyCode)
            const localVarPath = `/journeys/{journeyCode}`
                .replace(`{${"journeyCode"}}`, encodeURIComponent(String(journeyCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJourneyDefinitions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/journeys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyDefinitionsApi - functional programming interface
 */
export const JourneyDefinitionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyDefinitionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyDefinitionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJourneyDefinition(createJourneyDefinitionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.createJourneyDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a journey definition by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteJourneyDefinition(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.deleteJourneyDefinition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<JourneyDefinitionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyDefinitionsByCode(journeyCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.getJourneyDefinitionsByCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJourneyDefinitions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<JourneyDefinitionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJourneyDefinitions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyDefinitionsApi.listJourneyDefinitions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyDefinitionsApi - factory interface
 */
export const JourneyDefinitionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyDefinitionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new journey definition
         * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyDefinitionResponse> {
            return localVarFp.createJourneyDefinition(createJourneyDefinitionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a journey definition by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteJourneyDefinition(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all versions of a journey definition
         * @param {string} journeyCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<JourneyDefinitionResponse>> {
            return localVarFp.getJourneyDefinitionsByCode(journeyCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all journey definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJourneyDefinitions(options?: RawAxiosRequestConfig): AxiosPromise<Array<JourneyDefinitionResponse>> {
            return localVarFp.listJourneyDefinitions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyDefinitionsApi - object-oriented interface
 */
export class JourneyDefinitionsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new journey definition
     * @param {CreateJourneyDefinitionRequest} createJourneyDefinitionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createJourneyDefinition(createJourneyDefinitionRequest: CreateJourneyDefinitionRequest, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).createJourneyDefinition(createJourneyDefinitionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a journey definition by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteJourneyDefinition(id: string, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).deleteJourneyDefinition(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all versions of a journey definition
     * @param {string} journeyCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyDefinitionsByCode(journeyCode: string, options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).getJourneyDefinitionsByCode(journeyCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all journey definitions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listJourneyDefinitions(options?: RawAxiosRequestConfig) {
        return JourneyDefinitionsApiFp(this.configuration).listJourneyDefinitions(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * JourneyInstanceHistoryApi - axios parameter creator
 */
export const JourneyInstanceHistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstanceHistory: async (instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('getJourneyInstanceHistory', 'instanceId', instanceId)
            const localVarPath = `/journey-instances/{instanceId}/history`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (eventType !== undefined) {
                localVarQueryParameter['eventType'] = eventType;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyInstanceHistoryApi - functional programming interface
 */
export const JourneyInstanceHistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyInstanceHistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransitionHistoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstanceHistoryApi.getJourneyInstanceHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyInstanceHistoryApi - factory interface
 */
export const JourneyInstanceHistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyInstanceHistoryApiFp(configuration)
    return {
        /**
         * Retrieves the complete transition history for a specific journey instance in chronological order
         * @summary Get transition history for a journey instance
         * @param {string} instanceId ID of the journey instance
         * @param {string} [from] Filter history from this timestamp (ISO 8601)
         * @param {string} [to] Filter history to this timestamp (ISO 8601)
         * @param {string} [eventType] Filter by specific event type
         * @param {number} [limit] Maximum number of events to return
         * @param {number} [offset] Number of events to skip (for pagination)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<TransitionHistoryListResponse> {
            return localVarFp.getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyInstanceHistoryApi - object-oriented interface
 */
export class JourneyInstanceHistoryApi extends BaseAPI {
    /**
     * Retrieves the complete transition history for a specific journey instance in chronological order
     * @summary Get transition history for a journey instance
     * @param {string} instanceId ID of the journey instance
     * @param {string} [from] Filter history from this timestamp (ISO 8601)
     * @param {string} [to] Filter history to this timestamp (ISO 8601)
     * @param {string} [eventType] Filter by specific event type
     * @param {number} [limit] Maximum number of events to return
     * @param {number} [offset] Number of events to skip (for pagination)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyInstanceHistory(instanceId: string, from?: string, to?: string, eventType?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return JourneyInstanceHistoryApiFp(this.configuration).getJourneyInstanceHistory(instanceId, from, to, eventType, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * JourneyInstancesApi - axios parameter creator
 */
export const JourneyInstancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyInstance: async (createJourneyInstanceRequest: CreateJourneyInstanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createJourneyInstanceRequest' is not null or undefined
            assertParamExists('createJourneyInstance', 'createJourneyInstanceRequest', createJourneyInstanceRequest)
            const localVarPath = `/journey-instances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createJourneyInstanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstance: async (instanceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('getJourneyInstance', 'instanceId', instanceId)
            const localVarPath = `/journey-instances/{instanceId}`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEvent: async (instanceId: string, eventRequest: EventRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            assertParamExists('sendEvent', 'instanceId', instanceId)
            // verify required parameter 'eventRequest' is not null or undefined
            assertParamExists('sendEvent', 'eventRequest', eventRequest)
            const localVarPath = `/journey-instances/{instanceId}/events`
                .replace(`{${"instanceId"}}`, encodeURIComponent(String(instanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eventRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneyInstancesApi - functional programming interface
 */
export const JourneyInstancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneyInstancesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJourneyInstance(createJourneyInstanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.createJourneyInstance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyInstance(instanceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.getJourneyInstance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JourneyInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEvent(instanceId, eventRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneyInstancesApi.sendEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneyInstancesApi - factory interface
 */
export const JourneyInstancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneyInstancesApiFp(configuration)
    return {
        /**
         * 
         * @summary Start a new journey instance
         * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.createJourneyInstance(createJourneyInstanceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get journey instance by id
         * @param {string} instanceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.getJourneyInstance(instanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send event to a journey instance
         * @param {string} instanceId 
         * @param {EventRequest} eventRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig): AxiosPromise<JourneyInstanceResponse> {
            return localVarFp.sendEvent(instanceId, eventRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneyInstancesApi - object-oriented interface
 */
export class JourneyInstancesApi extends BaseAPI {
    /**
     * 
     * @summary Start a new journey instance
     * @param {CreateJourneyInstanceRequest} createJourneyInstanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createJourneyInstance(createJourneyInstanceRequest: CreateJourneyInstanceRequest, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).createJourneyInstance(createJourneyInstanceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get journey instance by id
     * @param {string} instanceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getJourneyInstance(instanceId: string, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).getJourneyInstance(instanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Send event to a journey instance
     * @param {string} instanceId 
     * @param {EventRequest} eventRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendEvent(instanceId: string, eventRequest: EventRequest, options?: RawAxiosRequestConfig) {
        return JourneyInstancesApiFp(this.configuration).sendEvent(instanceId, eventRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



