/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateJourneyInstanceRequest
 */
export interface CreateJourneyInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateJourneyInstanceRequest
     */
    journeyCode: string;
    /**
     * 
     * @type {number}
     * @memberof CreateJourneyInstanceRequest
     */
    version: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateJourneyInstanceRequest
     */
    context?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateJourneyInstanceRequest interface.
 */
export function instanceOfCreateJourneyInstanceRequest(value: object): value is CreateJourneyInstanceRequest {
    if (!('journeyCode' in value) || value['journeyCode'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function CreateJourneyInstanceRequestFromJSON(json: any): CreateJourneyInstanceRequest {
    return CreateJourneyInstanceRequestFromJSONTyped(json, false);
}

export function CreateJourneyInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJourneyInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'journeyCode': json['journeyCode'],
        'version': json['version'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function CreateJourneyInstanceRequestToJSON(json: any): CreateJourneyInstanceRequest {
    return CreateJourneyInstanceRequestToJSONTyped(json, false);
}

export function CreateJourneyInstanceRequestToJSONTyped(value?: CreateJourneyInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'journeyCode': value['journeyCode'],
        'version': value['version'],
        'context': value['context'],
    };
}

