/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventRequest
 */
export interface EventRequest {
    /**
     * 
     * @type {string}
     * @memberof EventRequest
     */
    event: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventRequest
     */
    payload?: { [key: string]: any; };
}

/**
 * Check if a given object implements the EventRequest interface.
 */
export function instanceOfEventRequest(value: object): value is EventRequest {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function EventRequestFromJSON(json: any): EventRequest {
    return EventRequestFromJSONTyped(json, false);
}

export function EventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function EventRequestToJSON(json: any): EventRequest {
    return EventRequestToJSONTyped(json, false);
}

export function EventRequestToJSONTyped(value?: EventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'payload': value['payload'],
    };
}

