/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventInfo
 */
export interface EventInfo {
    /**
     * Type of the event that triggered the transition
     * @type {string}
     * @memberof EventInfo
     */
    type: string;
    /**
     * Event-specific data
     * @type {{ [key: string]: any; }}
     * @memberof EventInfo
     */
    data?: { [key: string]: any; };
}

/**
 * Check if a given object implements the EventInfo interface.
 */
export function instanceOfEventInfo(value: object): value is EventInfo {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EventInfoFromJSON(json: any): EventInfo {
    return EventInfoFromJSONTyped(json, false);
}

export function EventInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function EventInfoToJSON(json: any): EventInfo {
    return EventInfoToJSONTyped(json, false);
}

export function EventInfoToJSONTyped(value?: EventInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': value['data'],
    };
}

