/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { State } from './State';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State';
import type { TransitionResponse } from './TransitionResponse';
import {
    TransitionResponseFromJSON,
    TransitionResponseFromJSONTyped,
    TransitionResponseToJSON,
    TransitionResponseToJSONTyped,
} from './TransitionResponse';

/**
 * 
 * @export
 * @interface JourneyDefinitionResponse
 */
export interface JourneyDefinitionResponse {
    /**
     * 
     * @type {string}
     * @memberof JourneyDefinitionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JourneyDefinitionResponse
     */
    journeyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof JourneyDefinitionResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof JourneyDefinitionResponse
     */
    version?: number;
    /**
     * 
     * @type {Array<State>}
     * @memberof JourneyDefinitionResponse
     */
    states?: Array<State>;
    /**
     * 
     * @type {Array<TransitionResponse>}
     * @memberof JourneyDefinitionResponse
     */
    transitions?: Array<TransitionResponse>;
    /**
     * 
     * @type {boolean}
     * @memberof JourneyDefinitionResponse
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JourneyDefinitionResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the JourneyDefinitionResponse interface.
 */
export function instanceOfJourneyDefinitionResponse(value: object): value is JourneyDefinitionResponse {
    return true;
}

export function JourneyDefinitionResponseFromJSON(json: any): JourneyDefinitionResponse {
    return JourneyDefinitionResponseFromJSONTyped(json, false);
}

export function JourneyDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyDefinitionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'journeyCode': json['journeyCode'] == null ? undefined : json['journeyCode'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'states': json['states'] == null ? undefined : ((json['states'] as Array<any>).map(StateFromJSON)),
        'transitions': json['transitions'] == null ? undefined : ((json['transitions'] as Array<any>).map(TransitionResponseFromJSON)),
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function JourneyDefinitionResponseToJSON(json: any): JourneyDefinitionResponse {
    return JourneyDefinitionResponseToJSONTyped(json, false);
}

export function JourneyDefinitionResponseToJSONTyped(value?: JourneyDefinitionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'journeyCode': value['journeyCode'],
        'name': value['name'],
        'version': value['version'],
        'states': value['states'] == null ? undefined : ((value['states'] as Array<any>).map(StateToJSON)),
        'transitions': value['transitions'] == null ? undefined : ((value['transitions'] as Array<any>).map(TransitionResponseToJSON)),
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

