/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationInfo
 */
export interface PaginationInfo {
    /**
     * Number of events returned in this page
     * @type {number}
     * @memberof PaginationInfo
     */
    limit?: number;
    /**
     * Number of events skipped
     * @type {number}
     * @memberof PaginationInfo
     */
    offset?: number;
    /**
     * Whether there are more events available
     * @type {boolean}
     * @memberof PaginationInfo
     */
    hasNext?: boolean;
    /**
     * Whether there are previous events available
     * @type {boolean}
     * @memberof PaginationInfo
     */
    hasPrevious?: boolean;
}

/**
 * Check if a given object implements the PaginationInfo interface.
 */
export function instanceOfPaginationInfo(value: object): value is PaginationInfo {
    return true;
}

export function PaginationInfoFromJSON(json: any): PaginationInfo {
    return PaginationInfoFromJSONTyped(json, false);
}

export function PaginationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
    };
}

export function PaginationInfoToJSON(json: any): PaginationInfo {
    return PaginationInfoToJSONTyped(json, false);
}

export function PaginationInfoToJSONTyped(value?: PaginationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'hasNext': value['hasNext'],
        'hasPrevious': value['hasPrevious'],
    };
}

