/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StateType = {
    Initial: 'INITIAL',
    Intermediate: 'INTERMEDIATE',
    Final: 'FINAL'
} as const;
export type StateType = typeof StateType[keyof typeof StateType];


export function instanceOfStateType(value: any): boolean {
    for (const key in StateType) {
        if (Object.prototype.hasOwnProperty.call(StateType, key)) {
            if (StateType[key as keyof typeof StateType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateTypeFromJSON(json: any): StateType {
    return StateTypeFromJSONTyped(json, false);
}

export function StateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateType {
    return json as StateType;
}

export function StateTypeToJSON(value?: StateType | null): any {
    return value as any;
}

export function StateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StateType {
    return value as StateType;
}

