/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { TransitionHistoryEventResponse } from './TransitionHistoryEventResponse';
import {
    TransitionHistoryEventResponseFromJSON,
    TransitionHistoryEventResponseFromJSONTyped,
    TransitionHistoryEventResponseToJSON,
    TransitionHistoryEventResponseToJSONTyped,
} from './TransitionHistoryEventResponse';

/**
 * 
 * @export
 * @interface TransitionHistoryListResponse
 */
export interface TransitionHistoryListResponse {
    /**
     * ID of the journey instance
     * @type {string}
     * @memberof TransitionHistoryListResponse
     */
    instanceId?: string;
    /**
     * 
     * @type {Array<TransitionHistoryEventResponse>}
     * @memberof TransitionHistoryListResponse
     */
    events?: Array<TransitionHistoryEventResponse>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof TransitionHistoryListResponse
     */
    pagination?: PaginationInfo;
    /**
     * Total number of events in history
     * @type {number}
     * @memberof TransitionHistoryListResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TransitionHistoryListResponse interface.
 */
export function instanceOfTransitionHistoryListResponse(value: object): value is TransitionHistoryListResponse {
    return true;
}

export function TransitionHistoryListResponseFromJSON(json: any): TransitionHistoryListResponse {
    return TransitionHistoryListResponseFromJSONTyped(json, false);
}

export function TransitionHistoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionHistoryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'instanceId': json['instanceId'] == null ? undefined : json['instanceId'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(TransitionHistoryEventResponseFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function TransitionHistoryListResponseToJSON(json: any): TransitionHistoryListResponse {
    return TransitionHistoryListResponseToJSONTyped(json, false);
}

export function TransitionHistoryListResponseToJSONTyped(value?: TransitionHistoryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instanceId': value['instanceId'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(TransitionHistoryEventResponseToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
        'totalCount': value['totalCount'],
    };
}

