/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitionResponse
 */
export interface TransitionResponse {
    /**
     * 
     * @type {string}
     * @memberof TransitionResponse
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof TransitionResponse
     */
    event?: string;
    /**
     * 
     * @type {string}
     * @memberof TransitionResponse
     */
    target?: string;
    /**
     * Optional SpEL expression for conditional transitions
     * @type {string}
     * @memberof TransitionResponse
     */
    condition?: string;
}

/**
 * Check if a given object implements the TransitionResponse interface.
 */
export function instanceOfTransitionResponse(value: object): value is TransitionResponse {
    return true;
}

export function TransitionResponseFromJSON(json: any): TransitionResponse {
    return TransitionResponseFromJSONTyped(json, false);
}

export function TransitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'event': json['event'] == null ? undefined : json['event'],
        'target': json['target'] == null ? undefined : json['target'],
        'condition': json['condition'] == null ? undefined : json['condition'],
    };
}

export function TransitionResponseToJSON(json: any): TransitionResponse {
    return TransitionResponseToJSONTyped(json, false);
}

export function TransitionResponseToJSONTyped(value?: TransitionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'event': value['event'],
        'target': value['target'],
        'condition': value['condition'],
    };
}

