/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventInfo } from './EventInfo';
import {
    EventInfoFromJSON,
    EventInfoFromJSONTyped,
    EventInfoToJSON,
    EventInfoToJSONTyped,
} from './EventInfo';

/**
 * 
 * @export
 * @interface TransitionHistoryEventResponse
 */
export interface TransitionHistoryEventResponse {
    /**
     * Unique identifier for the history event
     * @type {string}
     * @memberof TransitionHistoryEventResponse
     */
    id: string;
    /**
     * ID of the journey instance
     * @type {string}
     * @memberof TransitionHistoryEventResponse
     */
    instanceId: string;
    /**
     * Previous state before transition
     * @type {string}
     * @memberof TransitionHistoryEventResponse
     */
    fromState: string;
    /**
     * New state after transition
     * @type {string}
     * @memberof TransitionHistoryEventResponse
     */
    toState: string;
    /**
     * 
     * @type {EventInfo}
     * @memberof TransitionHistoryEventResponse
     */
    event: EventInfo;
    /**
     * When the transition occurred (ISO 8601)
     * @type {Date}
     * @memberof TransitionHistoryEventResponse
     */
    timestamp: Date;
    /**
     * Additional context information
     * @type {{ [key: string]: any; }}
     * @memberof TransitionHistoryEventResponse
     */
    metadata?: { [key: string]: any; };
    /**
     * Sequence number for ordering same-millisecond events
     * @type {number}
     * @memberof TransitionHistoryEventResponse
     */
    sequenceNumber?: number;
}

/**
 * Check if a given object implements the TransitionHistoryEventResponse interface.
 */
export function instanceOfTransitionHistoryEventResponse(value: object): value is TransitionHistoryEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('instanceId' in value) || value['instanceId'] === undefined) return false;
    if (!('fromState' in value) || value['fromState'] === undefined) return false;
    if (!('toState' in value) || value['toState'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function TransitionHistoryEventResponseFromJSON(json: any): TransitionHistoryEventResponse {
    return TransitionHistoryEventResponseFromJSONTyped(json, false);
}

export function TransitionHistoryEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionHistoryEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'instanceId': json['instanceId'],
        'fromState': json['fromState'],
        'toState': json['toState'],
        'event': EventInfoFromJSON(json['event']),
        'timestamp': (new Date(json['timestamp'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'sequenceNumber': json['sequenceNumber'] == null ? undefined : json['sequenceNumber'],
    };
}

export function TransitionHistoryEventResponseToJSON(json: any): TransitionHistoryEventResponse {
    return TransitionHistoryEventResponseToJSONTyped(json, false);
}

export function TransitionHistoryEventResponseToJSONTyped(value?: TransitionHistoryEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'instanceId': value['instanceId'],
        'fromState': value['fromState'],
        'toState': value['toState'],
        'event': EventInfoToJSON(value['event']),
        'timestamp': value['timestamp'].toISOString(),
        'metadata': value['metadata'],
        'sequenceNumber': value['sequenceNumber'],
    };
}

