/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitionRequest
 */
export interface TransitionRequest {
    /**
     * 
     * @type {string}
     * @memberof TransitionRequest
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof TransitionRequest
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof TransitionRequest
     */
    target: string;
    /**
     * Optional SpEL expression for conditional transitions
     * @type {string}
     * @memberof TransitionRequest
     */
    condition?: string;
}

/**
 * Check if a given object implements the TransitionRequest interface.
 */
export function instanceOfTransitionRequest(value: object): value is TransitionRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function TransitionRequestFromJSON(json: any): TransitionRequest {
    return TransitionRequestFromJSONTyped(json, false);
}

export function TransitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'event': json['event'],
        'target': json['target'],
        'condition': json['condition'] == null ? undefined : json['condition'],
    };
}

export function TransitionRequestToJSON(json: any): TransitionRequest {
    return TransitionRequestToJSONTyped(json, false);
}

export function TransitionRequestToJSONTyped(value?: TransitionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'event': value['event'],
        'target': value['target'],
        'condition': value['condition'],
    };
}

