/* tslint:disable */
/* eslint-disable */
/**
 * Journey Orchestrator API
 * Platform service responsible for executing configurable journeys using a state machine model. The service is business-agnostic and manages journey definitions and journey instances driven by events. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TransitionResponse {
    /**
     * Source state reference by name (legacy)
     */
    'source'?: string;
    /**
     * Target state reference by name (legacy)
     */
    'target'?: string;
    /**
     * Source state reference by ID (new). Populated when available.
     */
    'sourceStateId'?: string;
    /**
     * Target state reference by ID (new). Populated when available.
     */
    'targetStateId'?: string;
    'event'?: string;
    /**
     * Optional SpEL expression for conditional transitions
     */
    'condition'?: string;
}

